# docker-compose.yml

services:
  bash:
    build:
      context: ./app
      dockerfile: Dockerfile
    stdin_open: true  # Keep STDIN open for an interactive session
    tty: true         # Allocate a pseudo-TTY for the container
