services:
  db:
    image: postgres:15           # Use the official PostgreSQL image
    container_name: sample_django_project_postgres_db
    env_file:
      - /opt/docker_volume/sample_django_project/secrets/.env  # Use the .env file for environment variables
    networks:
      nginx_container_app_network:
        ipv4_address: 172.18.0.11 # Static IP address for PostgreSQL
    volumes:
      - /opt/docker_volume/sample_django_project/database:/var/lib/postgresql/data

  app:
    build:
      context: ./django
      dockerfile: Dockerfile
    image: sample_django_project:latest
    container_name: sample_django_project
    ports:
      - "8000:8000"
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000
    networks:
      nginx_container_app_network:
        ipv4_address: 172.18.0.10
    depends_on:
      - db                           # Ensure PostgreSQL is ready before starting Django
    env_file:
      - /opt/docker_volume/sample_django_project/secrets/.env  # Use the .env file for environment variables

networks:
  nginx_container_app_network:
    external: true

volumes:
  postgres_data:                    # Define the volume for persisting PostgreSQL data
