version: '3.8'

services:
  django:
    image: django:latest  # Alternatively, you could build from your own Dockerfile
    container_name: test_local
    command: gunicorn app.wsgi:application --bind 0.0.0.0:8000 --workers 3  # Use Gunicorn as WSGI server
    volumes:
      - ./app:/usr/src/app  # Mount your app's code to the container
    working_dir: /usr/src/app  # Set working directory inside the container
    networks:
      app_network:
        ipv4_address: 172.18.0.5  # Assign a static IP to the Django container
    ports:
      - "8000:8000"  # Expose Gunicorn on port 8000
    restart: always  # Restart container on failure/reboot

networks:
  nginx_container_app_network:
    external: true  # Use the already existing app_network bridge
